 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetoffresstage;

import javax.swing.JOptionPane;

/**
 *
 * @author kilavuz
 */
public class MenuCreationEntreprise extends javax.swing.JFrame {

    /**
     * Creates new form MenuCreationEntreprise
     */
    public MenuCreationEntreprise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNom1 = new javax.swing.JTextField();
        jLnom = new javax.swing.JLabel();
        jLadresse = new javax.swing.JLabel();
        jLadresseCP = new javax.swing.JLabel();
        jLadresseV = new javax.swing.JLabel();
        jLMail = new javax.swing.JLabel();
        jLTel = new javax.swing.JLabel();
        jLSecteurActivite = new javax.swing.JLabel();
        jTextAdresse = new javax.swing.JTextField();
        jTextAdresseCP = new javax.swing.JTextField();
        jTextAdresseV = new javax.swing.JTextField();
        jTextMail = new javax.swing.JTextField();
        jTextTel = new javax.swing.JTextField();
        jTextSecteurActivite = new javax.swing.JTextField();
        btnenvoyer = new javax.swing.JButton();
        btnannuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(68, 231, 206));

        jLabel1.setForeground(new java.awt.Color(251, 237, 237));
        jLabel1.setText("CREATION D'UNE ENTREPRISE");

        jTextNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNom1ActionPerformed(evt);
            }
        });

        jLnom.setForeground(new java.awt.Color(249, 231, 231));
        jLnom.setText("Nom de l'entreprise :");

        jLadresse.setForeground(new java.awt.Color(245, 235, 235));
        jLadresse.setText("Adresse ( Numéro et rue ) :");

        jLadresseCP.setForeground(new java.awt.Color(251, 225, 225));
        jLadresseCP.setText("Adresse ( Code postal ) :");

        jLadresseV.setBackground(new java.awt.Color(237, 234, 231));
        jLadresseV.setForeground(new java.awt.Color(253, 243, 243));
        jLadresseV.setText("Adresse ( Ville ) :");

        jLMail.setForeground(new java.awt.Color(250, 243, 243));
        jLMail.setText("Mail du contact :");

        jLTel.setForeground(new java.awt.Color(248, 241, 241));
        jLTel.setText("Téléphone du contact :");

        jLSecteurActivite.setForeground(new java.awt.Color(252, 245, 245));
        jLSecteurActivite.setText("Secteur d'activité de l'entreprise : ");

        btnenvoyer.setText("Envoyer");
        btnenvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenvoyerActionPerformed(evt);
            }
        });

        btnannuler.setText("Annuler");
        btnannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnannulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(btnenvoyer)
                .addGap(50, 50, 50)
                .addComponent(btnannuler)
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLadresse)
                                .addComponent(jLnom)
                                .addComponent(jLadresseCP))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextAdresseCP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLadresseV)
                                .addComponent(jLMail)
                                .addComponent(jLTel)
                                .addComponent(jLSecteurActivite))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextAdresseV, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextSecteurActivite, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnannuler)
                    .addComponent(btnenvoyer))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLnom)
                        .addComponent(jTextNom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLadresse))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jTextAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLadresseCP)
                        .addComponent(jTextAdresseCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLadresseV)
                        .addComponent(jTextAdresseV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLMail)
                        .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLTel)
                        .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLSecteurActivite)
                        .addComponent(jTextSecteurActivite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNom1ActionPerformed

    private void btnannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnannulerActionPerformed
         this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnannulerActionPerformed

    private void btnenvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenvoyerActionPerformed
         
        if (jTextNom1.getText().isEmpty() || jTextAdresse.getText().isEmpty() 
                  || jTextAdresseCP.getText().isEmpty() || 
                  jTextAdresseV.getText().isEmpty() || jTextMail.getText().isEmpty()
                  || jTextTel.getText().isEmpty() || 
                  jTextSecteurActivite.getText().isEmpty()){
          
              JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs"
                    + " s'il vous plaît");
          }
        
        else{ Entreprise e1 = new Entreprise(jTextNom1.getText(), jTextAdresse.getText(),
          jTextAdresseCP.getText(), jTextAdresseV.getText(), jTextMail.getText(),
          jTextTel.getText(), jTextSecteurActivite.getText());
          MainProjet.lesEntreprises.add(e1);
          
          
          
          String nom = evt.getActionCommand();
          if(nom.equals("Envoyer"))
          {
          JOptionPane.showMessageDialog(this, "Entreprise ajoutée");
          this.dispose();// TODO add your handling code here:
          }}
    }//GEN-LAST:event_btnenvoyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCreationEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCreationEntreprise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnannuler;
    private javax.swing.JButton btnenvoyer;
    private javax.swing.JLabel jLMail;
    private javax.swing.JLabel jLSecteurActivite;
    private javax.swing.JLabel jLTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLadresse;
    private javax.swing.JLabel jLadresseCP;
    private javax.swing.JLabel jLadresseV;
    private javax.swing.JLabel jLnom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextAdresse;
    private javax.swing.JTextField jTextAdresseCP;
    private javax.swing.JTextField jTextAdresseV;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JTextField jTextNom1;
    private javax.swing.JTextField jTextSecteurActivite;
    private javax.swing.JTextField jTextTel;
    // End of variables declaration//GEN-END:variables
}
