/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetoffresstage;

/**
 *
 * @author kilavuz
 */
public class MenuConsulter extends javax.swing.JFrame {

    /**
     * Creates new form MenuConsulter
     */
    int compteur=0;
    
    
    public MenuConsulter() {
        initComponents();
      
         if (MainProjet.lesOffres.size() != 0){
             
            OffreStage OS = MainProjet.lesOffres.get(0);
               
                jTextNom.setText(OS.getEntreprise().getNom());
                jTextVilleStage.setText(OS.getEntreprise().getAdresseVilleEntreprise());
                jTextMail.setText(OS.getEntreprise().getMailEntreprise());
                jTextDomaine.setText(OS.getDomaineOffre());
                jTextLibelle.setText(OS.getLibelléOffre());
                jTextDateD.setText(OS.getDateDébutOffre());
                jTextDateF.setText(OS.getDuréeOffre());
                jTextDescriptif.setText(OS.getDesciptifOffre());
                 
        
         }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextVilleStage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnprécédent = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        btnfermer = new javax.swing.JButton();
        jTextMail = new javax.swing.JTextField();
        jTextDomaine = new javax.swing.JTextField();
        jTextLibelle = new javax.swing.JTextField();
        jTextDateD = new javax.swing.JTextField();
        jTextDateF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDescriptif = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 134, 126));

        jLabel1.setForeground(new java.awt.Color(246, 249, 251));
        jLabel1.setText("CONSULTATION DES OFFRES DE STAGE");

        jLabel2.setBackground(new java.awt.Color(253, 252, 251));
        jLabel2.setForeground(new java.awt.Color(252, 236, 236));
        jLabel2.setText("Nom de l'entreprise :");

        jTextNom.setEditable(false);
        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(251, 250, 250));
        jLabel3.setForeground(new java.awt.Color(248, 236, 236));
        jLabel3.setText("Ville du stage :");

        jTextVilleStage.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(237, 230, 230));
        jLabel4.setText("Mail contact :");

        jLabel5.setForeground(new java.awt.Color(249, 239, 239));
        jLabel5.setText("Domaine offre :");

        jLabel6.setForeground(new java.awt.Color(254, 247, 247));
        jLabel6.setText("Libellé de l'offre :");

        jLabel7.setForeground(new java.awt.Color(251, 246, 246));
        jLabel7.setText("Date de début du stage :");

        jLabel8.setForeground(new java.awt.Color(238, 235, 244));
        jLabel8.setText("Durée du stage :");

        jLabel9.setForeground(new java.awt.Color(254, 247, 247));
        jLabel9.setText("Description de l'offre :");

        btnprécédent.setText("Précédent");
        btnprécédent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprécédentActionPerformed(evt);
            }
        });

        btnsuivant.setText("Suivant");
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });

        btnfermer.setText("Fermer");
        btnfermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfermerActionPerformed(evt);
            }
        });

        jTextMail.setEditable(false);

        jTextDomaine.setEditable(false);

        jTextLibelle.setEditable(false);

        jTextDateD.setEditable(false);

        jTextDateF.setEditable(false);
        jTextDateF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDateFActionPerformed(evt);
            }
        });

        jTextDescriptif.setEditable(false);
        jTextDescriptif.setColumns(20);
        jTextDescriptif.setRows(5);
        jScrollPane1.setViewportView(jTextDescriptif);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextMail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDomaine, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextVilleStage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDateD)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextDateF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnprécédent)
                                .addGap(39, 39, 39)
                                .addComponent(btnsuivant)
                                .addGap(44, 44, 44)
                                .addComponent(btnfermer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextVilleStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDomaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTextLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextDateD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDateF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnprécédent)
                        .addComponent(btnfermer))
                    .addComponent(btnsuivant))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        
    }//GEN-LAST:event_jTextNomActionPerformed

    private void btnprécédentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprécédentActionPerformed
            if (compteur-1 >=0){
            compteur--;
            
             OffreStage StageAvant =MainProjet.lesOffres.get(compteur);
        
            jTextNom.setText(StageAvant.getEntreprise().getNom());
            jTextVilleStage.setText(StageAvant.getEntreprise().getAdresseVilleEntreprise());
            jTextMail.setText(StageAvant.getEntreprise().getMailEntreprise());
            jTextDomaine.setText(StageAvant.getDomaineOffre());
            jTextLibelle.setText(StageAvant.getLibelléOffre());
            jTextDateD.setText(StageAvant.getDateDébutOffre());
            jTextDateF.setText(StageAvant.getDuréeOffre());
            jTextDescriptif.setText(StageAvant.getDesciptifOffre());
            
            }
            
            
// TODO add your handling code here:
    }//GEN-LAST:event_btnprécédentActionPerformed

    private void jTextDateFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDateFActionPerformed
        
    }//GEN-LAST:event_jTextDateFActionPerformed

    private void btnfermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfermerActionPerformed
         this.dispose();
         // Permet de fermer la page
    }//GEN-LAST:event_btnfermerActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
      
         if (compteur+1 < MainProjet.lesOffres.size()){
        compteur++;
        
        OffreStage StageSuivant =MainProjet.lesOffres.get(compteur);
        
         jTextNom.setText(StageSuivant.getEntreprise().getNom());
            jTextVilleStage.setText(StageSuivant.getEntreprise().getAdresseVilleEntreprise());
            jTextMail.setText(StageSuivant.getEntreprise().getMailEntreprise());
            jTextDomaine.setText(StageSuivant.getDomaineOffre());
            jTextLibelle.setText(StageSuivant.getLibelléOffre());
            jTextDateD.setText(StageSuivant.getDateDébutOffre());
            jTextDateF.setText(StageSuivant.getDuréeOffre());
            jTextDescriptif.setText(StageSuivant.getDesciptifOffre());
       
    }//GEN-LAST:event_btnsuivantActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConsulter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfermer;
    private javax.swing.JButton btnprécédent;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDateD;
    private javax.swing.JTextField jTextDateF;
    private javax.swing.JTextArea jTextDescriptif;
    private javax.swing.JTextField jTextDomaine;
    private javax.swing.JTextField jTextLibelle;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextVilleStage;
    // End of variables declaration//GEN-END:variables
}
